{{- range $name, $svc := .Values.services}}
{{- if and $svc.enabled $svc.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
  labels:
    app: {{$name}}
spec:
  type: {{$svc.serviceType | default "ClusterIP"}}
  selector:
    app: {{$name}}
  ports:
    - port: {{$svc.port}}
      targetPort: {{$svc.containerPort | default $svc.port}}
{{- end}}
{{- end}}