apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount }}{{ .Values.serviceAccount.name | default "online-boutique" }}{{ else }}"online-boutique"{{ end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
