apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: online-boutique
      containers:
        - name: server
          image: 730335441285.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/cartservice:6dbead2cda359b8d3b85d7628ddc28f7414bde57-30780838023
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: redis-cart:6379
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  selector:
    app: cartservice
  ports:
    - port: 7070
      targetPort: 7070