apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: chart
    releaseName: online-boutique
    namespace: online-boutique
    valuesFile: chart/values.yaml
    additionalValuesFiles:
      - chart/values-images.yaml
