apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: online-boutique
      containers:
        - name: loadgenerator
          image: 730335441285.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/loadgenerator:6dbead2cda359b8d3b85d7628ddc28f7414bde57-30780838023
          command: ["locust"]
          args: ["--host=http://frontend:80", "--web-port=8089"]
          env:
            - name: FRONTEND_ADDR
              value: frontend:80
            - name: USERS
              value: "10"
            - name: RATE
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: online-boutique
spec:
  type: ClusterIP
  selector:
    app: loadgenerator
  ports:
    - name: web
      port: 8089
      targetPort: 8089
