kube-prometheus-stack:
  grafana:
    sidecar:
      dashboards:
        searchNamespace: ALL
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: "Main Org."
        org_role: "Admin"
    additionalDataSources:
      - name: Jaeger
        type: jaeger
        uid: jaeger
        url: http://jaeger.observability:16686
        access: proxy
