{{- range $name, $svc := .Values.services}}
{{- if and $svc.enabled $svc.metrics $svc.metrics.enabled}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{$name}}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{$name}}
  endpoints:
    - port: {{ $svc.portName | default "tcp" }}
      path: {{ $svc.metrics.path | default "/metrics" }}
      interval: {{ $svc.metrics.interval | default "30s" }}
{{- end}}
{{- end}}
